Update files for ORION cluster

diff --git a/src/Utility/Cluster_files/run_orion b/src/Utility/Cluster_files/run_orion
--- a/src/Utility/Cluster_files/run_orion
+++ b/src/Utility/Cluster_files/run_orion
@@ -1,18 +1,22 @@
-#!/bin/bash  
-#SBATCH -J R210g  
-#SBATCH -A XXX
-##queues: 'windfall' max 450 nodes (no walltime limit but lower priority)
-#SBATCH -q windfall
-#SBATCH --partition=orion
-#SBATCH -N 10
-#SBATCH -n 400
-#SBATCH -t 10:00:00  
+#!/bin/bash --login
+
+#SBATCH -D .
+#SBATCH -J CORIE
+#SBATCH -A nosofs
+#SBATCH -p orion
+##queues: 'windfall' max 450 nodes (no walltime limit but lower priority; for quick turn-around try <=8 hrs)
+###40 cores/node
+#SBATCH -n 40
 #SBATCH --exclusive
+#SBATCH -t 02:00:00  
 #SBATCH -o myout
 #SBATCH -e err2.out
-#SBATCH --mail-user=yjzhang@vims.edu
-#SBATCH --mail-type=ALL  #send email for start, end and fail
+##SBATCH --mail-user=yjzhang@vims.edu
+##SBATCH --mail-type=all  #send email for start, end and fail
 
-module load 
+set -e
+ulimit -s unlimited 
 
-srun ./pschism_
+module load intel/2020 impi/2020 netcdf/4.7.2-parallel
+
+srun ./pschism_ORION_TVD-VL
